# Generated by Django 2.0.8 on 2019-01-09 11:57

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='race',
            name='race_date',
            field=models.DateTimeField(default='2000-01-01', verbose_name='date of race'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2),
        ),
    ]
